### ISSUE TITLE
Won't compile on Manjaro Linux

### ISSUE THREAD

**Issue by cregist** [decenomy/DSW#36]
I made a git clone of your repository
then:

>./autogen.sh
>./configure
>make

The compile chokes at:

>httpserver.cpp:74:10: error: ‘deque’ in namespace ‘std’ does not name a template type
>   74 |     std::deque<WorkItem*> queue;
>      |          ^~~~~
>httpserver.cpp:32:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?
>   31 | #include <event2/keyvalq_struct.h>
>  +++ |+#include <deque>
>   32 | 

and continues with  some similar errors.

Obviously there is a missing definition or declaration, but, alas, I am not a programmer.

**Comment by bedri** [comment]
Hello @cregist,
You can use static build given in https://github.com/decenomy/DSW/blob/SAPP-develop/build_linux.sh script.

We know about that std::deque error in dynamic build but since some OS has different versions of the libraries than another OS, we cannot standardize the dynamic build. So we suggest static build.

**Comment by bedri** [comment]
@cregist 
```bash
# Upgrade the system and install required dependencies
	sudo apt update
	sudo apt install git zip unzip build-essential libtool bsdmainutils autotools-dev autoconf pkg-config automake python3 libqt5svg5-dev -y

# Compile dependencies
	cd depends
	make -j$(echo $CPU_CORES) HOST=x86_64-pc-linux-gnu 
	cd ..

# Compile
	./autogen.sh
	./configure --enable-glibc-back-compat --prefix=$(pwd)/depends/x86_64-pc-linux-gnu LDFLAGS="-static-libstdc++" --enable-cxx --enable-static --disable-shared --disable-debug --disable-tests --disable-bench --with-pic CPPFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768" CXXFLAGS="-fPIC -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768"
	make -j$(echo $CPU_CORES) HOST=x86_64-pc-linux-gnu
```

**Comment by cregist** [comment]
I think that I noted that I was not running a debian style Linux. 
sudo apt whatever result in a not found error; the build_linux.sh script won't work.
I had to have the prereqs installed to get ./configure to work.
I'll try the static build.
Thanks

**Comment by Trittium** [comment]
Hi @cregist, we are supporting the build process on Ubuntu 18.04, and we are currently testing Ubuntu 20.04 to be the supported distribution for our development environment.

you can follow the multiple instructions that are available on: https://github.com/decenomy/DSW/blob/develop/doc/build-unix.md and https://github.com/decenomy/DSW/blob/develop/doc/ in order to adapt the build process to Manjaro.
